---
  - hosts: all
    sudo: yes
    tasks:
    - name: install ppa
      shell: add-apt-repository ppa:linuxuprising/java

    - name: install installer
      shell: apt-get install oracle-java10-installer

    - name: set default
      shell: apt-get install oracle-java10-set-default


