---
  - hosts: all
    sudo: yes
    tasks:
    - name: install ppa
      shell: add-apt-repository ppa:openjdk-r/ppa

    - name: apt update
      shell: apt-get update

    - name: install open jdk
      shell: apt-get install openjdk-8-jdk


