---
- hosts: all

  tasks:

    - name: example copying file with owner and permissions
      copy:
        src: /packer/bin/gs-spring-boot-0.1.0.jar
        dest: /home/ubuntu/node-app/
        owner: ubuntu
        group: ubuntu
        mode: 0777

