pipeline {
  agent {
       docker {
          image 'maven:3.3.3'
        }
    }
  environment {
        EMAIL_RECIPIENTS = 'arulkr1967@gmail.com'
  }
  stages {

    stage('install') {
      steps {
          sh 'mkdir /root/packer'
          dir("/root/packer") {
            sh '''
                wget https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip
                wget https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip
                apt-get update
                apt-get install unzip -y
                unzip packer_1.1.3_linux_amd64.zip
                unzip terraform_0.11.1_linux_amd64.zip
                mv packer /usr/local/bin/packer
                mv terraform /usr/local/bin/terraform
                rm packer_1.1.3_linux_amd64.zip
                rm terraform_0.11.1_linux_amd64.zip
              '''
          }
      }
    }
    stage('Build') {
      steps {
        dir("${JENKINS_HOME}/workspace/revoultduptest/complete") {
          sh 'mvn package'
        }
      }
    }
    stage('Create Packer AMI') {
        steps {
          withCredentials([
            usernamePassword(credentialsId: 'ada90a34-30ef-47fb-8a7f-a97fe69ff93f', passwordVariable: 'AWS_SECRET', usernameVariable: 'AWS_KEY')
          ]) {
            sh 'packer build -var aws_access_key=${AWS_KEY} -var aws_secret_key=${AWS_SECRET} packer/packer.json'
        }
      }
    }
    stage('AWS Deployment') {
      steps {
          withCredentials([
            usernamePassword(credentialsId: 'ada90a34-30ef-47fb-8a7f-a97fe69ff93f', passwordVariable: 'AWS_SECRET', usernameVariable: 'AWS_KEY'),
            usernamePassword(credentialsId: '2facaea2-613b-4f34-9fb7-1dc2daf25c45', passwordVariable: 'REPO_PASS', usernameVariable: 'REPO_USER'),
          ]) {
            sh 'rm -rf revtest_practice1'
            sh 'git clone https://github.com/arulkumarkandasamy/revtest_practice1.git'
            sh '''
               cd revtest_practice1
               terraform init
               terraform apply -auto-approve -var access_key=${AWS_KEY} -var secret_key=${AWS_SECRET}
               git add terraform.tfstate
               git -c user.name="Arulkumar Kandasamy" -c user.email="karul43@yahoo.co.in" commit -m "terraform state update from Jenkins"
               git push https://${REPO_USER}:${REPO_PASS}@github.com/arulkumarkandasamy/revtest_practice1.git master
            '''
        }
      }
    }
  }
  
  }
